name: Hello world workflow

on:
  push:
    branches:
       - master
  pull_request:
    branches:
       - master
  issues:
    types: [opened] 
  workflow_dispatch: 

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: hello world
         run: echo "hello world"
         shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
       - name: goodbye
         run: echo "goodbye"
         shell: bash
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
       - name: "dump github context"
         run: echo '${{ toJSON(github.event) }}' | jq
         shell: bash
       - name: Create comment
         uses: peter-evans/create-or-update-comment@v2
         with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'  
